<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Ambiente' => $baseDir . '/app/model/Ambiente.class.php',
    'Cadastro' => $baseDir . '/app/model/Cadastro.class.php',
    'Cardapio' => $baseDir . '/app/model/Cardapio.class.php',
    'Conexao' => $baseDir . '/app/model/Conexao.class.php',
    'Contato' => $baseDir . '/app/model/Contato.class.php',
    'Home' => $baseDir . '/app/model/Home.class.php',
    'Login' => $baseDir . '/app/model/Login.class.php',
    'Rotas' => $baseDir . '/app/model/Rotas.class.php',
    'SmartyConfig' => $baseDir . '/app/model/SmartyConfig.class.php',
    'conect' => $baseDir . '/app/model/conect.php',
);
