<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit682f763fca13fd235e912a1fc5647ffa
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Ambiente' => __DIR__ . '/../..' . '/app/model/Ambiente.class.php',
        'Cadastro' => __DIR__ . '/../..' . '/app/model/Cadastro.class.php',
        'Cardapio' => __DIR__ . '/../..' . '/app/model/Cardapio.class.php',
        'Conexao' => __DIR__ . '/../..' . '/app/model/Conexao.class.php',
        'Contato' => __DIR__ . '/../..' . '/app/model/Contato.class.php',
        'Home' => __DIR__ . '/../..' . '/app/model/Home.class.php',
        'Login' => __DIR__ . '/../..' . '/app/model/Login.class.php',
        'Rotas' => __DIR__ . '/../..' . '/app/model/Rotas.class.php',
        'SmartyConfig' => __DIR__ . '/../..' . '/app/model/SmartyConfig.class.php',
        'conect' => __DIR__ . '/../..' . '/app/model/conect.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit682f763fca13fd235e912a1fc5647ffa::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit682f763fca13fd235e912a1fc5647ffa::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit682f763fca13fd235e912a1fc5647ffa::$classMap;

        }, null, ClassLoader::class);
    }
}
